export const endpoints = {
    auth: {
        signIn: "/auth/sign-in",
        signUp: "/auth/sign-up",
        refresh: "/auth/refresh",
        revoke: "/auth/revoke",
        forgot: "/auth/forgot-password",
        reset: "/auth/reset-password",
        verify: "/auth/verify-otp",
    },
    account: {
        list: "/admin/account",
        create: "/admin/account",
        detail: (id: number) => `/admin/account/${id}`,
        update: (id: number) => `/admin/account/${id}`,
        lock: (id: number) => `/admin/account/lock/${id}`,
        unlock: (id: number) => `/admin/account/unlock/${id}`,
    },
    profile: {
        get: "/profile",
        updateInfo: "/profile/update-information",
        updatePassword: "/profile/update-password",
    },
    report: {
        list: "/admin/report",
    },
    comment: {
        list: "/admin/comment",
        hide: (id: number) => `/admin/comment/hide/${id}`,
        unhide: (id: number) => `/admin/comment/unhide/${id}`,
        byDocument: (documentId: number) => `/comment/document/${documentId}`,
        create: "/comment",
        delete: (id: number) => `/comment/${id}`,
    },
    bookmark: {
        list: "/bookmark",
        save: "/bookmark",
        delete: (documentId: number) => `/bookmark/${documentId}`,
    },
    tag: {
        list: "/admin/tag",
        detail: (id: number) => `/admin/tag/${id}`,
        create: "/admin/tag",
        update: (id: number) => `/admin/tag/${id}`,
        delete: (id: number) => `/admin/tag/delete/${id}`,
        restore: (id: number) => `/admin/tag/restore/${id}`,
    },
    faculty: {
        list: "/admin/faculty",
        detail: (id: number) => `/admin/faculty/${id}`,
        create: "/admin/faculty",
        update: (id: number) => `/admin/faculty/${id}`,
        delete: (id: number) => `/admin/faculty/delete/${id}`,
        restore: (id: number) => `/admin/faculty/restore/${id}`,
    },
    major: {
        list: "/admin/major",
        detail: (id: number) => `/admin/major/${id}`,
        create: "/admin/major",
        update: (id: number) => `/admin/major/${id}`,
        delete: (id: number) => `/admin/major/delete/${id}`,
        restore: (id: number) => `/admin/major/restore/${id}`,
    },
    subject: {
        list: "/admin/subject",
        detail: (id: number) => `/admin/subject/${id}`,
        create: "/admin/subject",
        update: (id: number) => `/admin/subject/${id}`,
        delete: (id: number) => `/admin/subject/delete/${id}`,
        restore: (id: number) => `/admin/subject/restore/${id}`,
    },
    group: {
        list: "/admin/documentgroup",
        approve: (id: number) => `/admin/documentgroup/approve/${id}`,
        reject: (id: number) => `/admin/documentgroup/reject/${id}`,
        myGroup: "/documentgroup/my/document-groups",
        published: "/documentgroup",
        create: "/documentgroup",
        update: (id: number) => `/documentgroup/${id}`,
        delete: (id: number) => `/documentgroup/delete/${id}`,
        restore: (id: number) => `/documentgroup/restore/${id}`
    },
    document: {
        list: "/admin/document",
        myList: "/document/my/documents",
        create: "/document",
        published: "/document",
        delete: (id: number) => `/document/delete/${id}`,
        restore: (id: number) => `/document/restore/${id}`,
        approve: (id: number) => `/admin/document/approve/${id}`,
        reject: (id: number) => `/admin/document/reject/${id}`,
        detail: (id: number) => `/document/${id}`,
        preview: (id: number) => `/document/preview/${id}`,
        download: (id: number) => `/document/download/${id}`,
    },
    payment: {
        create: "/payment",
        cancel: "/payment/cancel",
    },
    membership: {
        getCurrent: "/membership",
    },
    notification: {
        list: "/notifications",
        markAsRead: (id: number) => `/notifications/${id}/read`,
    },
};  